name: Build Release Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [air_firmware_esp32cam, air_firmware_esp32s3sense, air_firmware_esp32s3sense_ov5640]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install required Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools

    - name: Install PlatformIO latest
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build firmware
      run: |
        platformio run -d ${{ matrix.project }}

    - name: Create output directory
      run: mkdir -p release_zips

    - name: Zip firmware files
      run: |
        out="release_zips/${{ matrix.project }}.zip"
        zip -j "$out" \
          ${{ matrix.project }}/.pio/build/**/bootloader.bin \
          ${{ matrix.project }}/.pio/build/**/firmware.bin \
          ${{ matrix.project }}/.pio/build/**/flash_args \
          ${{ matrix.project }}/.pio/build/**/partitions.bin \
          ${{ matrix.project }}/.pio/build/**/ota_data_initial.bin || true

    - name: Upload zip as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.project }}.zip
        path: release_zips/${{ matrix.project }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create release tag
      id: tag
      run: echo "tag=release-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Create GitHub draft release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.tag }}
        name: Firmware Release ${{ env.tag }}
        draft: true
        files: |
          **/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
